# Build settings from your original file
[build]
  command = "yarn install && yarn build"
  publish = "dist"

# Function directory setting (already present)
[functions]
  directory = "netlify/functions"

# Redirect rule for API functions from your original file
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Single Page Application (SPA) redirect rule - MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200